In [273]:
#import your necessary libraries
import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC
from sklearn .metrics import accuracy_score, precision_score, f1_score, recall_score, confusion_matrix
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
import plotly.express as px
import seaborn as sns 
import joblib
import os
from sklearn.preprocessing import LabelEncoder

In [63]:
#import necessary dataset
df=pd.read_csv(r"C:\Users\itiol\Downloads\Resturant Dataset.csv", encoding="utf-8-sig")

In [64]:
df

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

In [65]:
#In the data set above, minor encoding inconsistencies were observed in certain text fields but did not affect the modelling process, as these
#variables were appropriately encoded or excluded.

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Restaurant ID         9551 non-null   int64  
 1   Restaurant Name       9551 non-null   object 
 2   Country Code          9551 non-null   int64  
 3   City                  9551 non-null   object 
 4   Address               9551 non-null   object 
 5   Locality              9551 non-null   object 
 6   Locality Verbose      9551 non-null   object 
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object 
 10  Average Cost for two  9551 non-null   int64  
 11  Currency              9551 non-null   object 
 12  Has Table booking     9551 non-null   object 
 13  Has Online delivery   9551 non-null   object 
 14  Is delivering now     9551 non-null   object 
 15  Switch to order menu 

In [67]:
df.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [68]:
df.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [69]:
df = df.dropna(subset=["Cuisines"])

In [70]:
df

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

In [71]:
df.isna().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                0
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [72]:
#drop irrelevant identifiers to improve model generalisation#

In [73]:
df = df.drop(columns=["Restaurant ID", "Restaurant Name", "Address", "Locality", "Locality Verbose", "Rating color", "Rating text", "Switch to order menu"])

In [74]:
df.columns

Index(['Country Code', 'City', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Price range',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [75]:
#identify categorical columns and encode# 
#Categorical columns are those stored as object data types,since ML models require numeric input, these objects were encode into numeric format#

In [76]:
#encode this - Has table booking, Has online delivery, Is delivering now     #(yes or no columns)#
binary_cols = ["Has Table booking", "Has Online delivery", "Is delivering now"]

for col in binary_cols:
    df[col] = df[col].map({"Yes": 1, "No": 0})

In [77]:
le = LabelEncoder()

In [78]:
#encode City# 
df["City"] = le.fit_transform(df["City"])

In [79]:
#encode Currency#
df["Currency"] = le.fit_transform(df["Currency"])

In [80]:
#encode Cuisines#
df["Cuisines"] = le.fit_transform(df["Cuisines"])

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9542 entries, 0 to 9550
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Country Code          9542 non-null   int64  
 1   City                  9542 non-null   int64  
 2   Longitude             9542 non-null   float64
 3   Latitude              9542 non-null   float64
 4   Cuisines              9542 non-null   int64  
 5   Average Cost for two  9542 non-null   int64  
 6   Currency              9542 non-null   int64  
 7   Has Table booking     9542 non-null   int64  
 8   Has Online delivery   9542 non-null   int64  
 9   Is delivering now     9542 non-null   int64  
 10  Price range           9542 non-null   int64  
 11  Aggregate rating      9542 non-null   float64
 12  Votes                 9542 non-null   int64  
dtypes: float64(3), int64(10)
memory usage: 1.0 MB


In [82]:
#Categorical variables were encoded using binary mapping for yes/no columns# 
#And also for multiclass features such as city, currency and cuisines#

In [83]:
df.head()

Country Code  City   Longitude   Latitude  Cuisines  Average Cost for two  \
0           162    73  121.027535  14.565443       920                  1100   
1           162    73  121.014101  14.553708      1111                  1200   
2           162    75  121.056831  14.581404      1671                  4000   
3           162    75  121.056475  14.585318      1126                  1500   
4           162    75  121.057508  14.584450      1122                  1500   

   Currency  Has Table booking  Has Online delivery  Is delivering now  \
0         0                  1                    0                  0   
1         0                  1                    0                  0   
2         0                  1                    0                  0   
3         0                  0                    0                  0   
4         0                  1                    0                  0   

   Price range  Aggregate rating  Votes  
0            3               4.8    314  
1            3               4.5    591  
2            4               4.4    270  
3            4               4.9    365  
4            4               4.8    229

In [84]:
df.shape

(9542, 13)

In [85]:
#build a linear regression model to predict restaurant ratings#
x = df.drop('Aggregate rating', axis=1)
y =df['Aggregate rating']

In [86]:
#inside x are the predictors stated below#
x= df[['Country Code', 'City', 'Longitude', 'Latitude', 'Average Cost for two', 'Currency', 'Has Table booking', 'Has Online delivery', 
'Is delivering now', 'Price range', 'Votes', 'Cuisines']]
y = df['Aggregate rating']

In [87]:
lr = LinearRegression()

In [88]:
#Training set = 80% data
#Testing set = 20% data

In [89]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [90]:
x_train

Country Code  City  Longitude   Latitude  Average Cost for two  \
8177             1    88  77.353663  28.574219                   450   
6401             1    87  77.134360  28.671141                   700   
81              30   120 -46.746958 -23.609207                   120   
1332             1    50  77.086080  28.482318                   300   
9041             1    88  77.339801  28.586405                   500   
...            ...   ...        ...        ...                   ...   
5743             1    87  77.052860  28.664641                   250   
5200             1    87  77.211180  28.536406                   300   
5399             1    87  77.128051  28.478595                   500   
869              1    43  77.305745  28.490062                   100   
7279             1    87  77.156650  28.705019                   300   

      Currency  Has Table booking  Has Online delivery  Is delivering now  \
8177         4                  0                    0                  0   
6401         4                  0                    0                  0   
81           1                  0                    0                  0   
1332         4                  0                    0                  0   
9041         4                  0                    1                  0   
...        ...                ...                  ...                ...   
5743         4                  0                    0                  0   
5200         4                  0                    1                  0   
5399         4                  0                    0                  0   
869          4                  0                    0                  0   
7279         4                  0                    0                  0   

      Price range  Votes  Cuisines  
8177            1      6      1699  
6401            2    112      1626  
81              4     11      1171  
1332            1      0      1275  
9041            2     93        58  
...           ...    ...       ...  
5743            1      1      1329  
5200            1    308       241  
5399            2      4      1306  
869             1      7       177  
7279            1      3      1699  

[7633 rows x 12 columns]

In [91]:
x_train.shape

(7633, 12)

In [92]:
y_train.shape

(7633,)

In [93]:
x_test.shape

(1909, 12)

In [94]:
y_test.shape

(1909,)

In [95]:
lr.fit(x_train, y_train)

LinearRegression()

In [96]:
print(x_train.isna().sum())

Country Code            0
City                    0
Longitude               0
Latitude                0
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Price range             0
Votes                   0
Cuisines                0
dtype: int64


In [98]:
y_pred =lr.predict(x_test)

In [99]:
y_pred

array([1.57635129, 3.23491258, 2.59244295, ..., 1.7896663 , 1.83547217,
       1.95082866])

In [100]:
y_test

7142    0.0
1860    4.1
4425    3.3
3219    3.9
8308    0.0
       ... 
5612    0.0
4061    0.0
8746    0.0
7678    0.0
4430    3.3
Name: Aggregate rating, Length: 1909, dtype: float64

In [101]:
#identify key features influencing ratings to show how much the rating changes
coefficients = pd.DataFrame({'Feature': x.columns,'Coefficient': lr.coef_})

In [102]:
coefficients.sort_values(by='Coefficient', ascending=False)

Feature   Coefficient
7    Has Online delivery  7.243423e-01
9            Price range  5.337551e-01
0           Country Code  7.078634e-03
2              Longitude  3.703007e-03
3               Latitude  2.452295e-03
10                 Votes  5.616564e-04
4   Average Cost for two  7.391709e-07
11              Cuisines -1.307636e-04
1                   City -3.232873e-03
6      Has Table booking -6.924793e-02
5               Currency -8.459897e-02
8      Is delivering now -1.549074e-01

In [103]:
#the top 3 influential features are - Has Online Delivery, Price Range, Is delivering now
#Has Online Delivery is the strongest predictor of 0.724 which means restaurant that offer online delivery tend to have ratings approximately
#0.724 points higher, holding other factors constant. Convenience contribute positively to premium ratings.
#Price Range of 0.534 means higher priced restaurants tend to have higher ratings suggesting premium restaurants recieve better reviews. 
#Is delivering now of -0.155 means restaurants currently delivering tend to have slightly lower ratings.This could suggest fast food or 
#lower end establishments  
#Other variables such as longitude,latitude, country code and votes demonstrated comparatively weaker influence

In [104]:
r2_score(y_test, y_pred)

0.3374226294592446

In [105]:
print(r2_score(y_test, y_pred)*100)

33.74226294592446


In [106]:
#MAE
#MSE
#RMSE
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

In [45]:
print('Your mean absolute error is', mae);
print('Your mean squared error is', mse);
print('Your root mean squared error is', rmse);

Your mean absolute error is 1.0150452392114444
Your mean squared error is 1.5173235142845123
Your root mean squared error is 1.2317968640504458


In [107]:
#MAE measures the average absolute difference between predicted and actual ratings.Restaurant reatings typically range from 0 to 5, So, on average, 
#the model's predictions deviate from actual ratings by approximately 1 rating point.
#MSE measures the actual squared differences between predicted and actual ratings and the value of 1.517 measures the average squared error. 
#RMSE is the square root of MSE and it predicts error of about 1.23 rating points. This further confirm the model prediction error, with larger 
#mistakes penalised more heavily.
#Also, the R2 score is 0.3374, meaning that the model explains approximately 33.74% of the variance in restaurant ratings.This indicates that 
#while the predictors contribute to explaining rating patterns, a substantial portion of variability (around 66%) remains unexplained by the model.
#Overall, the model demonstrates moderate predictive performance but leaves room for improvement. 

In [118]:
#Let us use RandomForestRegressorModel and after compare the two models
rf = RandomForestRegressor()

In [120]:
rf.fit(x_train, y_train)

RandomForestRegressor()

In [121]:
y_pred =rf.predict(x_test)

In [122]:
y_pred

array([0.   , 3.596, 3.231, ..., 0.   , 0.   , 3.543])

In [123]:
y_test

7142    0.0
1860    4.1
4425    3.3
3219    3.9
8308    0.0
       ... 
5612    0.0
4061    0.0
8746    0.0
7678    0.0
4430    3.3
Name: Aggregate rating, Length: 1909, dtype: float64

In [124]:
r2_score(y_test, y_pred)

0.9612886370613869

In [125]:
print(r2_score(y_test, y_pred)*100)

96.12886370613869


In [129]:
#MAE
#MSE
#RMSE
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

In [130]:
print('Your mean absolute error is', mae);
print('Your mean squared error is', mse);
print('Your root mean squared error is', rmse);

Your mean absolute error is 0.19512362493452062
Your mean squared error is 0.08865026767941325
Your root mean squared error is 0.29774194813531607


In [131]:
# Metric  LinearRegression RandomForestRegressor                                                       
#  MAE         1.015             0.193
#  MSE         1.517             0.087
#  RMSE        1.232             0.296
#  R^2         0.33              0.96
# Model comparison was conducted using MAE,MSE,RMSE and R^2. The RF achieved lower MAE,MSE,RMSE values indicating reduced prediction error.  
# While linear Regression achieved an R2 of 0.33, Random Forest achieved an R2 of 0.96,significantly outperforming linear regression and this
# indicate that the non linear relationship between variables play a substantial role in predicting restaurant ratings. 
# This also indicates that restaurant ratings exhibit nonlinear patterns.
# Therefore, Random Forest Regressor is selected as the better performing model. 

In [148]:
#Build a logistic regression model to predict whether the restaurant is high rated or low rated using predictors..  

In [149]:
x = df.drop(['Aggregate rating', 'Rating Category'],axis=1)
y =df['Rating Category']

In [150]:
x = df[['Country Code','City','Longitude', 'Latitude','Average Cost for two', 'Currency','Has Table booking','Has Online delivery','Is delivering now', 
'Price range','Votes', 'Cuisines']]
y = df['Rating Category']

In [151]:
# Write a function to convert aggregate rating to binary category
def encoder (rating):
    if rating > 4:
        return 1   # High rating
    else:
        return 0   # Low rating

In [152]:
df['Aggregate rating'].apply(encoder)

0       1
1       1
2       1
3       1
4       1
       ..
9546    1
9547    1
9548    0
9549    0
9550    0
Name: Aggregate rating, Length: 9542, dtype: int64

In [153]:
df['Rating Category'] = df['Aggregate rating'].apply(encoder)

In [154]:
y.value_counts()

Rating Category
0    8430
1    1112
Name: count, dtype: int64

In [156]:
##Training set = 80% data
##Testing set = 20% data

In [157]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [158]:
x_train 

Country Code  City  Longitude   Latitude  Average Cost for two  \
8177             1    88  77.353663  28.574219                   450   
6401             1    87  77.134360  28.671141                   700   
81              30   120 -46.746958 -23.609207                   120   
1332             1    50  77.086080  28.482318                   300   
9041             1    88  77.339801  28.586405                   500   
...            ...   ...        ...        ...                   ...   
5743             1    87  77.052860  28.664641                   250   
5200             1    87  77.211180  28.536406                   300   
5399             1    87  77.128051  28.478595                   500   
869              1    43  77.305745  28.490062                   100   
7279             1    87  77.156650  28.705019                   300   

      Currency  Has Table booking  Has Online delivery  Is delivering now  \
8177         4                  0                    0                  0   
6401         4                  0                    0                  0   
81           1                  0                    0                  0   
1332         4                  0                    0                  0   
9041         4                  0                    1                  0   
...        ...                ...                  ...                ...   
5743         4                  0                    0                  0   
5200         4                  0                    1                  0   
5399         4                  0                    0                  0   
869          4                  0                    0                  0   
7279         4                  0                    0                  0   

      Price range  Votes  Cuisines  
8177            1      6      1699  
6401            2    112      1626  
81              4     11      1171  
1332            1      0      1275  
9041            2     93        58  
...           ...    ...       ...  
5743            1      1      1329  
5200            1    308       241  
5399            2      4      1306  
869             1      7       177  
7279            1      3      1699  

[7633 rows x 12 columns]

In [159]:
x_train.shape

(7633, 12)

In [160]:
y_train.shape

(7633,)

In [161]:
x_test

Country Code  City  Longitude   Latitude  Average Cost for two  \
7142             1    87   0.000000   0.000000                   150   
1860             1    50  77.064227  28.467934                  1500   
4425             1    87  77.250660  28.543755                   250   
3219             1    87  77.230277  28.572796                  1500   
8308             1    88  77.331711  28.548867                   200   
...            ...   ...        ...        ...                   ...   
5612             1    87  77.219281  28.709557                   100   
4061             1    87   0.000000   0.000000                   500   
8746             1    88  77.385241  28.569480                   400   
7678             1    87  77.056812  28.622119                   400   
4430             1    87  77.252032  28.543064                   250   

      Currency  Has Table booking  Has Online delivery  Is delivering now  \
7142         4                  0                    0                  0   
1860         4                  0                    0                  0   
4425         4                  0                    1                  0   
3219         4                  1                    1                  0   
8308         4                  0                    0                  0   
...        ...                ...                  ...                ...   
5612         4                  0                    0                  0   
4061         4                  0                    0                  0   
8746         4                  0                    0                  0   
7678         4                  0                    0                  0   
4430         4                  0                    0                  0   

      Price range  Votes  Cuisines  
7142            1      2       586  
1860            3    105       147  
4425            1     55      1306  
3219            3    245      1031  
8308            1      0       518  
...           ...    ...       ...  
5612            1      0      1306  
4061            2      0       758  
8746            1      0      1650  
7678            1      3      1329  
4430            1     91       828  

[1909 rows x 12 columns]

In [162]:
x_test.shape

(1909, 12)

In [163]:
y_test.shape

(1909,)

In [164]:
y_train

8177    0
6401    0
81      1
1332    0
9041    0
       ..
5743    0
5200    0
5399    0
869     0
7279    0
Name: Rating Category, Length: 7633, dtype: int64

In [165]:
lr = LogisticRegression()

In [166]:
lr.fit(x_train, y_train)

C:\Users\itiol\OneDrive\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [167]:
y_pred_lr =lr.predict(x_test)

In [168]:
y_pred_lr

array([0, 0, 0, ..., 0, 0, 0])

In [169]:
y_test

7142    0
1860    1
4425    0
3219    0
8308    0
       ..
5612    0
4061    0
8746    0
7678    0
4430    0
Name: Rating Category, Length: 1909, dtype: int64

In [170]:
accuracy_score = accuracy_score(y_test,y_pred_lr)

In [171]:
print(accuracy_score)

0.9051859612362494


In [172]:
print(accuracy_score*100)

90.51859612362495


In [173]:
#The Confusion Matrix
print(confusion_matrix(y_test,y_pred_lr))

[[1646   47]
 [ 134   82]]


In [ ]:
#From the above confusion matrix
#1646 low rated restaurants were correctly classified. 
#47 restaurants were incorrectly classified as high rated. 
#82 high rated restaurants were correctly identified.
#134 restaurants were incorrectly identified as low rated. 
#This means that while the model performs well in identifying low-rated restaurants, but struggles more with correctly detecting high rating restaurants.

In [174]:
Label = ['0: Low rated restaurant', '1: High rated restaurant']

In [175]:
pd.DataFrame(data = confusion_matrix(y_test, y_pred_lr), index=Label, columns=Label)

0: Low rated restaurant  1: High rated restaurant
0: Low rated restaurant                      1646                        47
1: High rated restaurant                      134                        82

In [178]:
print(accuracy_score(y_test,y_pred_lr)*100)
print(precision_score(y_test,y_pred_lr)*100)
print(recall_score(y_test,y_pred_lr)*100)
print(f1_score(y_test,y_pred_lr)*100)

90.51859612362495
63.565891472868216
37.96296296296296
47.53623188405797


In [ ]:
#The model classified 90.5% of all restaurants correctly.However, because the dataset exhibited class imbalance, with approximately 88% low-rated 
#restaurants and 12% high-rated restaurants.This imbalance affected the classifier’s ability to accurately detect high-rated establishments, thus,
#accuracy alone does not fully reflect performance oh high rated restaurants. 
#Of all restaurants predicted as high rated, 63.6% were actually high rated.This tells us that the model does not mislabel low rated restaurants 
#as high rated.
#The model correctly identified only 37.96% of all actual high rated restautants. This is relatively low as it means the model misses many 
#high-rated restaurants, likely due to class imbalance. 
#The F1 score balances precision and recall. A score of 47.5% indicate moderate performance, reflecting the trade-off between correctly identifying high
#rated restaurants and avoiding false positives. 

In [179]:
#SINCE THE DATASET EXHIBIT A CLASS IMBALANCE, NOW LET US APPLY THE SMOTE TECHNIQUE TO REBALANCE THE MINORITY CLASS IN THE TRAINING DATA

In [180]:
#Build a logistic regression model to predict whether the restaurant is high rated or low rated using predictors.. 

In [181]:
x = df.drop(['Aggregate rating', 'Rating Category'],axis=1)
y =df['Rating Category']

In [182]:
# Write a function to convert aggregate rating to binary category
def encoder (rating):
    if rating > 4:
        return 1   # High rating
    else:
        return 0   # Low rating

In [183]:
df['Aggregate rating'].apply(encoder)

0       1
1       1
2       1
3       1
4       1
       ..
9546    1
9547    1
9548    0
9549    0
9550    0
Name: Aggregate rating, Length: 9542, dtype: int64

In [184]:
df['Rating Category'] = df['Aggregate rating'].apply(encoder)

In [185]:
y.value_counts()

Rating Category
0    8430
1    1112
Name: count, dtype: int64

In [186]:
#The above rating category exhibit a class imbalance- 8430 low rated restaurants versus 1112 high rated restaurants
# So resample them

In [187]:
#splitting dataset
x_train, x_test, y_train, y_test = train_test_split (x, y, test_size=0.2, random_state=42)

In [188]:
smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)

In [189]:
x_train_resampled.shape

(13474, 12)

In [190]:
y_train_resampled.shape

(13474,)

In [191]:
lr = LogisticRegression()

In [192]:
lr.fit(x_train_resampled, y_train_resampled)

C:\Users\itiol\OneDrive\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [193]:
y_pred_lr = lr.predict(x_test)

In [194]:
y_pred_lr

array([0, 1, 0, ..., 0, 0, 0])

In [195]:
accuracy_score = accuracy_score(y_test,y_pred_lr)

In [196]:
print(accuracy_score)

0.8648507071765322


In [197]:
print(accuracy_score*100)

86.48507071765323


In [198]:
#The Confusion Matrix
print(confusion_matrix(y_test,y_pred_lr))

[[1475  218]
 [  40  176]]


In [199]:
Label = ['0: Low rated restaurant', '1: High rated restaurant']

In [200]:
pd.DataFrame(data = confusion_matrix(y_test, y_pred_lr), index=Label, columns=Label)

0: Low rated restaurant  1: High rated restaurant
0: Low rated restaurant                      1475                       218
1: High rated restaurant                       40                       176

In [201]:
#From the above confusion matrix
#1475 low rated restaurants were correctly classified. 
#218 restaurants were incorrectly classified as high rated. 
#176 high rated restaurants were correctly identified.
#40 restaurants were incorrectly identified as low rated. 
#This means that the model performs well in identifying low-rated restaurants while significantly improving its ability to detect high rated resaurants.

In [204]:
print(accuracy_score(y_test,y_pred_lr)*100)
print(precision_score(y_test,y_pred_lr)*100)
print(recall_score(y_test,y_pred_lr)*100)
print(f1_score(y_test,y_pred_lr)*100)

86.48507071765323
44.67005076142132
81.48148148148148
57.70491803278689


In [ ]:
#The model classified 86.49% of all restaurants correctly.Although the dataset initially exhibited class imbalance, applying SMOTE helped rebalance the 
#training data and improve detection of high rated restaurants.So, accuracy alone does not fully refelct the classifier's performance on minority class.
#Of all restaurants predicted as high rated, 44.67% were actually high rated.While the model is now identifying more high-rated restaurants, it also 
#mislabel a notable number of low rated restaurants as high rated, reflecting a decrease in precision
#The model correctly identified 81.48% of all actual high rated restautants. This is a substantial improvement comapred to the non-SMOTE model. This 
#demonstrates that the classifier is now much more effective in detecting high rated restaurants. 
#The F1 score balances precision and recall. A score of 57.70%% indicate improved overall performance, comparede to the non-SMOTE model and ths reflect
#a better trade-off between identifying high rated restaurants and controlling false positives. 

In [246]:
#Let us use RandomForestClassifier and after compare the two models. Running the non-SMOTE and SMOTE model.
model = RandomForestClassifier()

In [247]:
model.fit(x_train, y_train)

RandomForestClassifier()

In [248]:
y_pred_model = model.predict(x_test)

In [249]:
y_pred_model

array([0, 0, 0, ..., 0, 0, 0])

In [250]:
y_test

7142    0
1860    1
4425    0
3219    0
8308    0
       ..
5612    0
4061    0
8746    0
7678    0
4430    0
Name: Rating Category, Length: 1909, dtype: int64

In [252]:
accuracy_score(y_test,y_pred_model)

0.926663174436878

In [253]:
print(accuracy_score(y_test,y_pred_model)*100)

92.6663174436878


In [254]:
#The Confusion Matrix
print(confusion_matrix(y_test,y_pred_model))

[[1650   43]
 [  97  119]]


In [ ]:
#From the above confusion matrix:
#1650 low-rated restaurants were correctly classified as low-rated.
#43 restaurants were incorrectly classified as high-rated.
#119 high-rated restaurants were correctly identified.
#97 restaurants were incorrectly classified as low-rated.
#This indicates that the Random Forest Classifier model(non-SMOTE model) performs strongly in identifying low-rated restaurants and shows 
#improved performance in detecting high-rated restaurants compared to the Logistic Regression model(non-SMOTE model).

In [255]:
Label = ['0: Low rated restaurant', '1: High rated restaurant']

In [256]:
pd.DataFrame(data = confusion_matrix(y_test, y_pred_model), index=Label, columns=Label)

0: Low rated restaurant  1: High rated restaurant
0: Low rated restaurant                      1650                        43
1: High rated restaurant                       97                       119

In [257]:
print(accuracy_score(y_test,y_pred_model)*100)
print(precision_score(y_test,y_pred_model)*100)
print(recall_score(y_test,y_pred_model)*100)
print(f1_score(y_test,y_pred_model)*100)

92.6663174436878
73.4567901234568
55.092592592592595
62.96296296296296


In [224]:
#The Random Forest model correctly classified 92.67% of all restaurants. However, because the dataset exhibits class imbalance, with a higher 
#proportiion of low-rated restaurants,accuracy alone does not fully reflect the model’s ability to detect high-rated restaurants.
#Of all restaurants predicted as high-rated, 73.45% were actually high-rated. This indicates that the Random Forest Classifier model is relatively 
#precise and less likely to incorrectly label low-rated restaurants as high-rated compared to the Logistic Regression Model.
#The model correctly identified 55.09% of all actual high-rated restaurants. This represent a clear improvement over (Logistic Regression model of 
#37.96%,).This means that the Random Forest Classifier model is better at detecting high-rated restaurants and reducing false negatives.
#The F1-score of 62.96% reflects a stronger balance between precision and recall. Compared to Logistic Regression, this indicates improved overall 
#classification performance, particularly in handling the minority(high-rated) class.Overall, the Random Forest Classifier model demonstrates superior 
#performance compared to Logistic Regression Model, especially in identifying high-rated restaurants while maintaining high overall accuracy.

In [258]:
#SMOTE WAS APPLIED TO EVALUATE WHETHER REBALANCING THE MINORITY CLASS WOULD IMPROVE THE PERFORMANCE OF THE RANDOM FOREST CLASSIFIER

In [259]:
smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)

In [260]:
x_train_resampled.shape

(13474, 12)

In [261]:
y_train_resampled.shape

(13474,)

In [262]:
model = RandomForestClassifier()

In [263]:
model.fit(x_train_resampled, y_train_resampled)

RandomForestClassifier()

In [264]:
y_pred_model = model.predict(x_test)

In [265]:
y_pred_model

array([0, 0, 0, ..., 0, 0, 0])

In [266]:
accuracy_score = accuracy_score(y_test,y_pred_model)

In [267]:
print(accuracy_score)

0.9203771608171818


In [268]:
print(accuracy_score*100)

92.03771608171817


In [269]:
#The Confusion Matrix
print(confusion_matrix(y_test,y_pred_model))

[[1611   82]
 [  70  146]]


In [270]:
Label = ['0: Low rated restaurant', '1: High rated restaurant']

In [271]:
pd.DataFrame(data = confusion_matrix(y_test, y_pred_model), index=Label, columns=Label)

0: Low rated restaurant  1: High rated restaurant
0: Low rated restaurant                      1611                        82
1: High rated restaurant                       70                       146

In [274]:
print(accuracy_score(y_test,y_pred_model)*100)
print(precision_score(y_test,y_pred_model)*100)
print(recall_score(y_test,y_pred_model)*100)
print(f1_score(y_test,y_pred_model)*100)

92.03771608171817
64.03508771929825
67.5925925925926
65.76576576576578


In [ ]:
#While the SMOTE slightly reduced overall accuracy and precision, it significantly improved recall and resulted in a higher F1 score. This indicates 
#improved identification of high rated restaurants. However, since the original Random Forest Classifier Model already performed strongly and also 
#achieved higher precision and accuracy, the original Random Forest Classifier model(without SMOTE) will be used for final comparison.

In [ ]:
#Comparison Table 

# Model	                   SMOTE	     Accuracy	Precision	  Recall	   F1
#Logistic Regression	   Yes	         86.49%	    44.67%	      81.48%	   57.70%
#Random Forest Classifier  No	         92.67%	    73.45%	      55.09%	   62.96%

In [ ]:
#Final Comparison Table - TASK 4
# Regression Model (Prediction Ratings)
#Model	                  MAE	     MSE        RMSE	   R²
#Linear Regression        1.02	     1.52       1.23	   0.33
#Random Forest Regressor  0.19	     0.08       0.29	   0.96

# Classification Model (High vs Low rating)
# Model	                   SMOTE	     Accuracy	Precision	  Recall	   F1
#Logistic Regression	   Yes	         86.49%	    44.67%	      81.48%	   57.70%
#Random Forest Classifier  No	         92.67%	    73.45%	      55.09%	   62.96%

In [ ]:
# Random Forest Regressor dramatically outperformed Linear Regression because there is strong evidence of non-linear relationship in restaurant ratings. 
#It achieved substantially lower prediction error and higher explanatory power 0f 0.96. It must be noted that restaurant ratings are influenced by 
#customer behaviour, pricing patterns, location dynamics, engagements.
#In the classification model, Random Forest Classifier demonstrated superior overall performance achieving higher accuracy,precision and F1 score 
#compared to Logistic Regression. The Random Forest Classifier provided a better overall balance and stability. It was also less sensitive to noise.

#Different models perform differently on the same dataset because different assumptions are made on the same dataset. Linear regression models struggle
#to capture the full structure of the data (real world business data) because of its complex behavioural patterns and non-linear relationships. For 
#example, the linear regression model fit in for a linear decision boundary, so when Random  Forest Regressor was applied, it automatically handled
#outliers better and was also less sensitive to scaling. The classification models, particularly the logistic model was more sensitive to class
#imbalance but random Forest Classifier handled the imbalance robustly. This means different algorithms respond differrently to data distribution 
#issues.  

# If given more time, I would improve by using more advanced imbalance techniques such as SMOTE cobined with Tomek links or Cost-Sensitive Learning or 
#Balanced Random Forest. It can help to generate a better recall-precision balance for minority class detection. 